version: 2
updates:
  - package-ecosystem: npm
    directory: /
    registries: "*"
    schedule:
      interval: daily
registries:
  github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.GH_READ_PACKAGES_TOKEN}}
